services:
  build:
    build: .
    volumes:
      - ./dist:/app/dist
    command: sh -c "cp -r /usr/share/nginx/html/* /app/dist/"

  deploy:
    image: alpine/git
    depends_on:
      build:
        condition: service_completed_successfully
    volumes:
      - .:/repo
    working_dir: /repo
    environment:
      - GITHUB_TOKEN
    command: >
      sh -c '
        git init &&
        git remote add origin https://$GITHUB_TOKEN@github.com/oxcl/bug-free-waddle.git &&
        git checkout -b gh-pages &&
        git add dist -f &&
        git commit -m "Deploy to GitHub Pages" &&
        git push -f origin gh-pages
      '
